homeassistant:
  base_url: "https://hass.nickwhyte.com"
  token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIyOTQzMDUzMzc5NDY0YzkzYjJiNmQ4NzAxOGI3NGMwNSIsImlhdCI6MTc2NTE5MDg4MSwiZXhwIjoyMDgwNTUwODgxfQ.2rRWy-oxi7wdA7qSJFXHIfhnQpv2RYTIVnYTOoTgk7U"
  verify_tls: true
plant:
  grid:
    max_import_kw: 13.0
    max_export_kw: 13.0
    realtime_grid_power:
      type: home_assistant
      entity: sensor.hass_energy_grid_power_smoothed_1m
    
    realtime_price_import:
      type: home_assistant
      entity: sensor.amber_general_price
    realtime_price_export:
      type: home_assistant
      entity: sensor.amber_feed_in_price

    price_import_forecast:
      type: home_assistant
      platform: amberelectric
      entity: sensor.amber_general_forecast
      use_advanced_price_forecast: true
    price_export_forecast:
      type: home_assistant
      platform: amberelectric
      entity: sensor.amber_feed_in_forecast
      use_advanced_price_forecast: true
    
    import_forbidden_periods:
      - start: "14:55"
        end: "21:05"

  load:
    # Note: Load power should have controlled loads subtracted from it.
    realtime_load_power:
      type: home_assistant
      entity: sensor.hass_energy_load_power_smoothed_1m
    
    # load_forecast: # We could implement a history based forecast (fetching home-assistant history)

  inverters:
    # DC coupled PV + Battery inverter example.
    - name: Primary
      peak_power_kw: 10.0
      ac_efficiency_pct: 96.0 # Efficiency converting AC to DC or DC to AC
      pv:
        - capacity_kw: 6.65
          realtime_power:
            type: home_assistant
            entity: sensor.hass_energy_pv_power_smoothed_1m

          forecast:
            type: home_assistant
            platform: solcast
            entities:
              - sensor.solcast_pv_forecast_forecast_today
              - sensor.solcast_pv_forecast_forecast_tomorrow
              - sensor.solcast_pv_forecast_forecast_day_3
            # type: solcast_api
            # In the future the user could provide parameters to allow us to request
            # forecasts from an external service. 
            # For now, users will retrieve forecasts from Home Assistant.
      battery:
        - capacity_kwh: 41.9
          min_soc_pct: 10.0
          max_soc_pct: 100.0

          # Specify a level of reserve to ensure some energy is always left in the battery
          # for grid outages or other emergencies.
          reserve_soc_pct: 20.0

          # Optional, if different from inverter parameters. e.g. DC-coupled batteries could charge 
          # from PV at a higher rate than the inverter peak power.
          max_charge_kw: 11.0 
          max_discharge_kw: 11.0

          state_of_charge_pct:
            type: home_assistant
            entity: sensor.inverter_battery_soc
          realtime_power:
            type: home_assistant
            entity: sensor.hass_energy_battery_power_smoothed_1m

          # dc_efficiency_pct: 98.0 # PV to battery efficiency - omitted, assume 100% efficiency of PV to battery
    
    # AC coupled PV inverter example.
    - name: Sungrow
      peak_power_kw: 5.0
      ac_efficiency_pct: 95.0
      pv:
        - capacity_kw: 3.35
          forecast:
            type: home_assistant
            platform: solcast
            entities:
              - sensor.solcast_pv_forecast_forecast_today
              - sensor.solcast_pv_forecast_forecast_tomorrow
              - sensor.solcast_pv_forecast_forecast_day_3
loads:
  - name: "Tessie"
    load_type: "controlled_ev"
    min_power_kw: 0.0
    max_power_kw: 7.4
    energy_kwh: 78.0
    connected:
      type: home_assistant
      entity: binary_sensor.tesla_wall_connector_vehicle_connected
    realtime_power:
      type: home_assistant
      entity: sensor.tessie_charger_power
    state_of_charge_pct:
      type: home_assistant
      entity: sensor.tessie_battery
    
    
    soc_incentives:
      - target_soc_pct: 40.0
        incentive: 0.08
      - target_soc_pct: 60.0
        incentive: 0.06
      - target_soc_pct: 80.0
        incentive: 0.04
      - target_soc_pct: 90.0
        incentive: 0.00 # << No monetary incentive to charge to 90%, but should satisfy self-use goals.
    # Note: should implement a penalty for switching on/off too frequently - prefer long sessions.
    # Note: should implement a way for user to specify desired departure time to ensure vehicle is charged 
    #       to specified SoC by then in the most optimal/cost effective way.

  # - name: "HWS"
  #   load_type: "nonvariable_load"
